# Generated by Django 5.1.5 on 2025-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='feedbackID')),
                ('username', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=4095)),
            ],
        ),
    ]
