# Generated by Django 5.1.5 on 2025-04-28 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_feedback_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('request_date', models.DateField(default=datetime.date(2025, 4, 28))),
                ('request_time', models.TimeField(default=datetime.time(10, 38, 26, 107786))),
            ],
        ),
    ]
