# Generated by Django 5.1.5 on 2025-04-28 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_feedback_username_feedback_submit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(10, 53, 1, 673937)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(10, 53, 1, 674154)),
        ),
    ]
