# Generated by Django 5.1.5 on 2025-04-30 02:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_feedback_submit_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submit_date',
            field=models.DateField(default=datetime.date(2025, 4, 30)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(10, 13, 58, 597145)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_date',
            field=models.DateField(default=datetime.date(2025, 4, 30)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(10, 13, 58, 597371)),
        ),
    ]
