# Generated by Django 5.1.5 on 2025-04-30 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_feedback_user_feedback_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(10, 14, 9, 306155)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(10, 14, 9, 306436)),
        ),
    ]
