# Generated by Django 5.1.5 on 2025-04-30 02:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_feedback_submit_time_alter_feedback_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(10, 22, 56, 4686)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(10, 22, 56, 4980)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestsupport', to=settings.AUTH_USER_MODEL),
        ),
    ]
