# Generated by Django 5.1.5 on 2025-04-30 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_feedback_submit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=4095),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(10, 29, 11, 517493)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(10, 29, 11, 517743)),
        ),
    ]
