# Generated by Django 5.1.5 on 2025-04-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_feedback_feedback_alter_feedback_submit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(21, 40, 34, 43344)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(21, 40, 34, 43605)),
        ),
    ]
