# Generated by Django 5.1.5 on 2025-05-01 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_feedback_submit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submit_date',
            field=models.DateField(default=datetime.date(2025, 5, 1)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='submit_time',
            field=models.TimeField(default=datetime.time(10, 34, 10, 155418)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_date',
            field=models.DateField(default=datetime.date(2025, 5, 1)),
        ),
        migrations.AlterField(
            model_name='requestsupport',
            name='request_time',
            field=models.TimeField(default=datetime.time(10, 34, 10, 155654)),
        ),
    ]
